### ISSUE TITLE
Presentation content for project defense

### ISSUE THREAD

**Issue by JoffreyLGT** [JoffreyLGT/e-commerce-mlops#132]
Préparer la présentation pour la soutenance du projet.

Rédiger le contenu au format markdown dans le wiki sur la page suivante : https://github.com/JoffreyLGT/e-commerce-mlops/wiki/Project-defense
L'objectif est de centraliser le fond, nous verrons ensuite la forme dans l'issue #133.

**Comment by JoffreyLGT** [comment]
@Landry-G01 Je te propose d'échanger sur le sujet directement dans cette issue.
Ainsi, nous conservons un historique des échanges.
Le bot Github postera les commentaires sur Slack pour nous notifier.

**Comment by JoffreyLGT** [comment]
Je viens de faire un diagramme détaillant les actions lorsqu'on effectue un commit.
https://github.com/JoffreyLGT/e-commerce-mlops/wiki/Project-defense

**Comment by JoffreyLGT** [comment]
Voici le diagramme d'architecture :

```mermaid

flowchart TB
    api[fa:fa-server API]
    ts[[fa:fa-scroll Training scripts]]
    mlf[[fa:fa-server Mlflow]]
    mlfs[fa:fa-brain Mlflow models serve]
    dbs[(PostgreSQL)]
    imgs[(Image storage)]:::dashed
    sig[[Signoz]]
    client{{fa:fa-users Client}}:::person
    ds{{fa:fa-vial Data scientist}}:::person

    subgraph fab:fa-docker db
    dbs
    imgs
    end

    subgraph fab:fa-docker backend
    api
    end

    subgraph fab:fa-docker datascience
    direction LR
    ts-->|Log training results|mlf
    mlf-->|Provide model to serve|mlfs
    end

    subgraph fab:fa-docker signoz
    sig:::dashed
    end

    classDef dashed stroke-dasharray: 5 5
    classDef person fill: #537188,color:#F9F5F6

    api-->|Store images|imgs
    mlfs-->|Read images|imgs
    ts-->|Read images|imgs
    api-->|Send telemetry and logs|sig
    api-->|Store information|dbs
    dbs-->|Retrieve information|api
    api-->|Send product info|mlfs
    mlfs-->|Send predictions|api
    client-->|Send product info|api
    api-->|Send prediction results|client

    ds-->|Start training|ts
    ds-->|Generate datasets|ts
    ds-->|Validate model version|mlf
```

**Comment by Landry-G01** [comment]
parfait 🙏

**Comment by JoffreyLGT** [comment]
Les icônes ne fonctionnent pas sur Github, j'espère qu'elles seront dans les slides.
![image](https://github.com/JoffreyLGT/e-commerce-mlops/assets/25529092/640e7317-92d7-4a4a-b7ab-ba3e2208d7a4)

**Comment by JoffreyLGT** [comment]
Done.
