### ISSUE TITLE
Mettre en place un outil de génération de la documentation

### ISSUE THREAD

**Issue by JoffreyLGT** [JoffreyLGT/e-commerce-mlops#54]
Voir pdoc et sphinx.

**Comment by JoffreyLGT** [comment]
@Landry-G01 Pourrais-tu m'indiquer l'état d'avancement de cette issue ?

**Comment by Landry-G01** [comment]
j'ai generé les fichiers rst des modules endpoits(login, prediction...), j'ai configuré les différents themes ..mais je n'arrive pas à generer la doc. j'ai tout essayé. Je peux te l'envoyer pour que tu vois si tu veux car je l'ai mis en attente.
Du coup je suis sur l'issues #79

**Comment by JoffreyLGT** [comment]
Quartz is setup and hosted on Github page at this address: https://joffreylgt.github.io/e-commerce-mlops/Developer/Documentation
