### ISSUE TITLE
 Création du modèle texte

### ISSUE THREAD

**Issue by Landry-G01** [JoffreyLGT/e-commerce-mlops#95]
🎯 Créer le modèle de prédiction de la catégorie du produit basé sur les mots

Actuellement, les modèles utilisés sont importés à partir de fichiers PKL.
Nous devons ajouter le code de création du modèle dans le projet Datascience pour nous permettre de faire des entrainements.

**Comment by JoffreyLGT** [comment]
@Landry-G01 Le code de création du modèle texte et du preprocesseur est déjà dans le projet backend/datascience.
Il faut le nettoyer et le mettre dans le projet Datascience.
